services:
    _defaults:
        autowire: true
        autoconfigure: true

    Netgen\Bundle\Ibexa2FABundle\Command\Remove2FAForUserCommand: ~

    Netgen\Bundle\Ibexa2FABundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Netgen\Bundle\Ibexa2FABundle\Listener\:
        resource: '../../Listener'

    Netgen\Bundle\Ibexa2FABundle\Core\:
        resource: '../../Core'

    Netgen\Bundle\Ibexa2FABundle\Core\SiteAccessAwareQueryExecutor: ~

    Netgen\Bundle\Ibexa2FABundle\Security\TwoFactorUserProviderDecorator:
        decorates: 'ibexa.security.user_provider'

    Netgen\Bundle\Ibexa2FABundle\Core\SiteAccessAwareAuthenticatorResolver:
        bind:
            $backupCodesEnabled: '%netgen_ibexa2fa.backup_codes.enabled%'

    Netgen\Bundle\Ibexa2FABundle\Core\Tab\TwoFAManagement:
        tags:
            - { name: ibexa.admin_ui.tab, group: location-view }

    Netgen\Bundle\Ibexa2FABundle\Core\EmailCodeGenerator:
        bind:
            $mailer: '@scheb_two_factor.security.email.auth_code_mailer'
            $digits: '%scheb_two_factor.email.digits%'

    Netgen\Bundle\Ibexa2FABundle\Listener\OnHttpRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    Netgen\Bundle\Ibexa2FABundle\Core\AuthCodeMailer:
        bind:
            $senderEmail: '%scheb_two_factor.email.sender_email%'
            $senderName: '%scheb_two_factor.email.sender_name%'
